# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DreamEasyApp', '0002_member_soundcloud_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
    ]
