# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamEasyApp', '0004_member_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.AddField(
            model_name='member',
            name='photo_url',
            field=models.CharField(default='http://www.stallerdental.com/wp-content/uploads/2016/12/user-icon.png', max_length=200),
        ),
    ]
