# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamEasyApp', '0007_auto_20171130_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(default='Add description of artists here', max_length=2500),
        ),
    ]
