# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamEasyApp', '0010_auto_20171215_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundcloudPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_link', models.CharField(max_length=2000)),
            ],
        ),
    ]
