# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamEasyApp', '0012_soundcloudpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundcloudpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
